### ISSUE TITLE
Gallery list returns null (empty) media items

### ISSUE THREAD

**Issue by dkarpienia** [agility/Agility-AspNetCore#3]
The gallery field in .NET CORE returns the media gallery information and has the correct number of items. But every item definition is null. 

{
  "Description": "",
  "Media": [
    {
      "IDSpecified": false,
      "MetaData": null,
      "ModifiedOnSpecified": false,
      "SizeSpecified": false,
      "SortOrderSpecified": false,
      "Thumbnails": null,
      "URL": null
    },
    {
      "IDSpecified": false,
      "MetaData": null,
      "ModifiedOnSpecified": false,
      "SizeSpecified": false,
      "SortOrderSpecified": false,
      "Thumbnails": null,
      "URL": null
    },
    {
      "IDSpecified": false,
      "MetaData": null,
      "ModifiedOnSpecified": false,
      "SizeSpecified": false,
      "SortOrderSpecified": false,
      "Thumbnails": null,
      "URL": null
    },
    {
      "IDSpecified": false,
      "MetaData": null,
      "ModifiedOnSpecified": false,
      "SizeSpecified": false,
      "SortOrderSpecified": false,
      "Thumbnails": null,
      "URL": null
    },
    {
      "IDSpecified": false,
      "MetaData": null,
      "ModifiedOnSpecified": false,
      "SizeSpecified": false,
      "SortOrderSpecified": false,
      "Thumbnails": null,
      "URL": null
    },
    {
      "IDSpecified": false,
      "MetaData": null,
      "ModifiedOnSpecified": false,
      "SizeSpecified": false,
      "SortOrderSpecified": false,
      "Thumbnails": null,
      "URL": null
    },
    {
      "IDSpecified": false,
      "MetaData": null,
      "ModifiedOnSpecified": false,
      "SizeSpecified": false,
      "SortOrderSpecified": false,
      "Thumbnails": null,
      "URL": null
    },
    {
      "IDSpecified": false,
      "MetaData": null,
      "ModifiedOnSpecified": false,
      "SizeSpecified": false,
      "SortOrderSpecified": false,
      "Thumbnails": null,
      "URL": null
    }
  ],
  "ModifiedOn": "2019-09-15T23:09:27.17",
  "ModifiedOnSpecified": true,
  "HasSecondaryData": true,
  "HasSecondaryDataSpecified": true,
  "ID": 7,
  "IDSpecified": true,
  "IsDeleted": false,
  "IsDeletedSpecified": true,
  "LanguageCode": null,
  "LastAccessDate": "2019-09-15T23:09:27.17",
  "LastAccessDateSpecified": true,
  "Name": "Locations galleries/Houston Gallery"
}

**Comment by jamesvidler** [comment]
This was an issue with the content server and has been resolved.
